# Define needed environment variables: the rest of the yml will most
# likely translate well to other similar projects, except for the
# "secure" passwords in the deploy stage, which have to be adapted.
env:
  global:
    - REPO_NAME="dotEsuS/liantis_ess_api" # releases will only work under this name

# this line routes the builds to Ubuntu 16.04
dist: xenial

# implicitly creates a venv for python in the VM (so pip syntax is "global")
language: python
python:
  - 3.7

# by default Travis starts every job from scratch. This speeds up things
cache: pip

# Perform pipeline only for events to master branch
branches:
  only:
  - master
  # this is needed for tag push actions (https://github.com/travis-ci/travis-ci/issues/8518#issuecomment-333489268)
  #   - /^v.*$/

#  https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  # - osx
  #- windows

install: pip install -U tox-travis
script: tox

after_success:
- sh ./travis/set_tags.sh


deploy:
  provider: releases
  skip_cleanup: true
  api_key: 
    secure: $GH_API_KEY
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*
  on:
    tags: true
    # branch: master # already filtered out in the "branches" section
    repo: "$REPO_NAME"
deploy:
  provider: pypi
  user: dotEsuS
  password:
    secure: $PYPI_PWD
  on:
    tags: true
    # branch: master # already filtered out in the "branches" section
    repo: "$REPO_NAME"


